name: pytest-logikal

services:
  validator:
    # Note: make sure to update the version in the docs/index.rst as well when changing it here!
    # Available versions: https://github.com/validator/validator/pkgs/container/validator/versions
    # Commit date: 2026-01-11
    image: ghcr.io/validator/validator@sha256:1e02132147c89c4d7e9c612a6cefcab35edb3dbc08fd19bab077dbabbb6fbce5
    ports: [{target: 8888}]
