extends: stylelint-config-standard
reportInvalidScopeDisables: true
reportNeedlessDisables: true
rules:
  color-named: never
  declaration-no-important: true
  function-url-no-scheme-relative: true
  custom-property-empty-line-before: null
  declaration-block-single-line-max-declarations: null
  color-hex-length: long
  font-weight-notation: named-where-possible
  font-family-name-quotes: always-unless-keyword

  # Stylistic rules
  # Note that these rules are deprecated but there is no proper replacement plugin to use yet
  color-hex-case: lower
  function-comma-newline-after: always-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never-single-line
  function-whitespace-after: always
  number-leading-zero: always
  number-no-trailing-zeros: true
  string-quotes: single
  unit-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  property-case: lower
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-block-semicolon-newline-after: always-multi-line
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-after: null
  block-closing-brace-space-before: always-single-line
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-newline-before: null
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: null
  selector-max-empty-lines: 0
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: always-single-line
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  indentation: 2
  max-empty-lines: 1
  max-line-length: {max_line_length}
  no-empty-first-line: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-missing-end-of-source-newline: true
